## Numpy-Day 1
### What is NumPy ?
NumPy stands for (Numerical Python) is a Python library that is commonly used for numerical computing. 
It provides a powerful N-dimensional array object, as well as tools for working with these arrays.

In [3]:
# Importing labraries 
import numpy as np

### Creating 1D Array

In [7]:
arr_1D=np.array([1,2,3,4,5])

In [8]:
print("Array::",arr)

Array:: [1 2 3 4 5]


In [9]:
# type of array
print("Type of Array :",type(arr))

Type of Array : <class 'numpy.ndarray'>


### Creating 2D Array

In [10]:
arr_2D=np.array([[1,2,3,4],[3,2,3,4],[6,7,8,9]])

In [11]:
arr_2D

array([[1, 2, 3, 4],
       [3, 2, 3, 4],
       [6, 7, 8, 9]])

In [12]:
# Check Dimension
arr_2D.ndim

2

In [13]:
# Check size 
arr_2D.size

12

In [14]:
#Check shape 
arr_2D.shape

(3, 4)

### Creating the array of (zeros) and (one's) 

In [15]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
np.ones((3,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones((3,3),dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###  Arange method in np array

In [19]:
arr1=np.arange(0,10,2)

In [20]:
arr1

array([0, 2, 4, 6, 8])

### Linspacein np
Return evenly spaced numbers over a specified interval.

In [21]:
arr2=np.linspace(1,5,4)

In [22]:
arr2

array([1.        , 2.33333333, 3.66666667, 5.        ])

### Reshape Method in np array 

In [24]:
reshap_arr=np.reshape(arr_2D,(6,2))

In [25]:
reshap_arr

array([[1, 2],
       [3, 4],
       [3, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [26]:
reshap_arr.flatten()

array([1, 2, 3, 4, 3, 2, 3, 4, 6, 7, 8, 9])

### Transpose Method in np array

In [27]:
np.transpose(reshap_arr)

array([[1, 3, 3, 3, 6, 8],
       [2, 4, 2, 4, 7, 9]])