## Numpy- Day 2

In [1]:
import numpy as np

In [2]:
arr_2D = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0],[1,1,1]])

In [3]:
print(arr_2D)

[[0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [9]:
rows = np.size(arr_2D, axis=0)  # 0 - rows  |  1 - cols
cols = np.size(arr_2D, axis=1)  # 0 - rows  |  1 - cols

In [11]:
print("NO. of Rows    : ",rows)
print("NO. of columns :",cols)

NO. of Rows    :  4
NO. of columns : 3


### print complete size of array

In [12]:
arr_size = np.size(arr_2D)

In [13]:
print("Size of Array:",arr_size)

Size of Array: 12


### Number of elements in rows and columns 

In [14]:
items_in_row = np.size(arr_2D, axis = 0) # give rows 
print("No. of items in a Rows = ", items_in_row )

No. of items in a Rows =  4


In [15]:
items_in_cols = np.size(arr_2D, axis = 1) # give columns 
print("No. of items in a Columns = ", items_in_cols )

No. of items in a Columns =  3
