## Numpy Day-3

### NumPy array shape Function

In [1]:
import numpy as np

In [2]:
arr_1D = np.array([1, 2, 3])

In [3]:
arr_1D

array([1, 2, 3])

In [8]:
shape_arr=np.shape(arr_1D)
print("Shape of Array :",shape_arr)

Shape of Array : (3,)


In [9]:
arr_2D = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
shape_2D=np.shape(arr_2D)
("Shape of 2D Array :",shape_2D)

('Shape of Array :', (3, 3))

In [11]:
arr_3D = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], 
[1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
shape_3D=np.shape(arr_3D)
print("Shape of 3D Array :",shape_3D)

Shape of 3D Array : (3, 3, 3)


In [12]:
arr_2D = np.array([[0, 1, 1,4], [1, 0, 1,0], [1, 1, 0,9],[1,3,4,8]]) 
print("2D array : \n", arr_2D) 

2D array : 
 [[0 1 1 4]
 [1 0 1 0]
 [1 1 0 9]
 [1 3 4 8]]


### NumPy Array Concatenation and Split

In [19]:
arr1=np.arange(1,10).reshape(3,3)

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2=np.arange(11,20).reshape(3,3)

In [24]:
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [25]:
Conn_arr=np.concatenate((arr1,arr2))
print(Conn_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


### Concatenate of arr1 and arr2 with axis


In [30]:
Conn_arr_ax=np.concatenate((arr1,arr2),axis=1)
print(Conn_arr_ax)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [31]:
Conn_arr=np.concatenate((arr1,arr2),axis=0)
print(Conn_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [34]:
np.split(arr1, 3 ,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [37]:
np.split(arr1[0], 3,)

[array([1]), array([2]), array([3])]

In [50]:
d1 = np.array([4,7,1,3,9,1,2,3,4,5])
np.split(d1, [3,3])

[array([4, 7, 1]), array([], dtype=int32), array([3, 9, 1, 2, 3, 4, 5])]

In [48]:
d1 = np.array(arr1[1])
np.split(d1, [2,1])

[array([4, 5]), array([], dtype=int32), array([5, 6])]