## Numpy Day-4

### Numpy Mathematical Functions

In [6]:
import numpy as np

In [7]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)

### Addition

In [4]:
add=arr1+arr2

In [5]:
add

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
addtion=np.add(arr1,arr2)

In [10]:
addtion

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### subtraction

In [13]:
sub=arr1-arr2-arr1

In [14]:
sub

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [15]:
subtraction=np.subtract(sub,arr1)
print(subtraction)

[[ -2  -4  -6]
 [ -8 -10 -12]
 [-14 -16 -18]]


### Multiply

In [18]:
mul=arr1*arr1
print(mul)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [19]:
cube=np.multiply(arr1,arr1,arr2)
cube

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### Division

In [29]:
arr2/arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.divide(arr1,arr2)

array([[1.        , 0.25      , 0.11111111],
       [0.0625    , 0.04      , 0.02777778],
       [0.02040816, 0.015625  , 0.01234568]])

## Matrix product


In [37]:
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [39]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## NumPy min(),max()

In [20]:
arr1.max()

9

In [21]:
arr1.max(axis=0)

array([7, 8, 9])

In [22]:
print(arr1.argmax())
print(arr1.max())

8
9


In [23]:
arr1.min()

1

In [24]:
arr1.min(axis=0)

array([1, 2, 3])