## Day-6 Numpy 

### Python NumPy random module

In [3]:
import numpy as np
import random

In [4]:
np.random.random(5)

array([0.63963966, 0.04973575, 0.66841068, 0.08365147, 0.55687978])

In [5]:
np.random.random((3,3))

array([[0.797424  , 0.82706806, 0.49140806],
       [0.32545365, 0.15304735, 0.59630958],
       [0.52481334, 0.33336455, 0.35505924]])

In [6]:
np.random.randint(1,6,(3,3))

array([[1, 2, 1],
       [4, 2, 4],
       [2, 1, 5]])

In [7]:
np.random.seed(10)
np.random.randint(1,6,(2,3,3))

array([[[2, 5, 1],
        [2, 4, 5],
        [2, 1, 2]],

       [[3, 1, 2],
        [1, 3, 1],
        [5, 4, 1]]])

In [8]:
# random 2d arr with rand function
np.random.rand(2,3,3)

array([[[0.81660184, 0.33607158, 0.89081653],
        [0.19812181, 0.03061665, 0.87761494],
        [0.72743551, 0.54088093, 0.13145815]],

       [[0.41366737, 0.77872881, 0.58390137],
        [0.18263144, 0.82608225, 0.10540183],
        [0.28357668, 0.06556327, 0.05644419]]])

In [10]:
x= [1,2,3,4] # list
choice_from_x = np.random.choice(x) # retun random single item from sequence
print(choice_from_x )

4
