## Day-7 Numpy

### Slicing concept in numpy


In [1]:
import numpy as np

In [4]:
mx_arr=np.arange(1,101).reshape(10,10)

In [5]:
mx_arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [8]:
mx_arr[2,2]

23

In [13]:
mx_arr[3:]

array([[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [18]:
mx_arr[1:2]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [19]:
mx_arr[0,0].ndim

0

In [22]:
mx_arr[:,2] #print all column in a row 

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [27]:
mx_arr[3:,2:-4] 

array([[33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66],
       [73, 74, 75, 76],
       [83, 84, 85, 86],
       [93, 94, 95, 96]])

In [30]:
mx_arr[1:5,1:5]

array([[12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45]])

In [32]:
mx_arr.itemsize

4

In [33]:
mx_arr.dtype

dtype('int32')